// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/auth.ts";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/courses.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/signin.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Courses.tsx";
import * as $$2 from "./islands/Header.tsx";
import * as $$3 from "./islands/Signin.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/auth.ts": $2,
    "./routes/api/joke.ts": $3,
    "./routes/courses.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/signin.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Courses.tsx": $$1,
    "./islands/Header.tsx": $$2,
    "./islands/Signin.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
